{{ if .Values.tabix.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tabix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tabix
  template:
    metadata:
      labels:
        app: tabix
    spec:
{{- if .Values.tabix.affinity }}
      affinity:
{{ toYaml .Values.tabix.affinity | indent 8 }}
      {{- end -}}
      {{- if .Values.tabix.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.tabix.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tabix.tolerations }}
      tolerations:
{{ toYaml .Values.tabix.tolerations | indent 8 }}
      {{- end }}
      containers:
      - name: tabix
        image: "spoonest/clickhouse-tabix-web-client:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 125m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 128Mi

{{ if .Values.tabix.lb.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: tabix-lb
spec:
  type: LoadBalancer
  ports:
  - name: ui
    port: {{ .Values.tabix.lb.port }}
    targetPort: 80
  selector:
    app: tabix
{{ end }}
{{ end }}
---
{{- if .Values.tabix.ingress.enabled -}}
{{- $httpPort := .Values.httpPort -}}
{{- $pathtype := .Values.tabix.ingress.pathtype -}}
{{- $ingressPath := .Values.tabix.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
{{- with .Values.tabix.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{- if .Values.tabix.ingress.className }}
  ingressClassName: {{ .Values.tabix.ingress.className | quote }}
  {{- end }}
{{- if .Values.tabix.ingress.tls }}
  tls:
  {{- if .ingressPath }}
  {{- range .Values.tabix.ingress.tls }}
  - hosts:
    {{- range .hosts }}
      - {{ . }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
{{- else }}
{{ toYaml .Values.tabix.ingress.tls | indent 4 }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.tabix.ingress.hosts }}
    {{- if $ingressPath }}
  - host: {{ . }}
    http:
      paths:
      - path: {{ $ingressPath }}
        pathType: {{ $pathtype }}
        backend:
          service:
            name: {{ $fullName }}
            port: 
              number: {{ $httpPort }}
  {{- else }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ $pathtype }}
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ .servicePort | default $httpPort }}
      {{- end }}
  {{- end }}
 {{- end }}
 {{- end }}