{{ if .Values.tabix.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tabix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tabix
  template:
    metadata:
      labels:
        app: tabix
    spec:
{{- if .Values.tabix.affinity }}
      affinity:
{{ toYaml .Values.tabix.affinity | indent 8 }}
      {{- end -}}
      {{- if .Values.tabix.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.tabix.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tabix.tolerations }}
      tolerations:
{{ toYaml .Values.tabix.tolerations | indent 8 }}
      {{- end }}
      containers:
      - name: tabix
        image: "spoonest/clickhouse-tabix-web-client:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 125m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 128Mi

{{ if .Values.tabix.lb.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: tabix-lb
spec:
  type: LoadBalancer
  ports:
  - name: ui
    port: {{ .Values.tabix.lb.port }}
    targetPort: 80
  selector:
    app: tabix
{{ end }}
{{ end }}